server:
  port: 8180


spring:
  application:
    name: seata-example-order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/seata
    username: root
    password: 123
  cloud:
    alibaba:
      seata:
        tx-service-group: xc_seata_test_group # 很重要，保持一致

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml


#  type-aliases-package: